services:
  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  address-service:
    build: .
    ports:
      - "3001:3001"
    container_name: address-service
    restart: always
volumes:
  postgres-data:  # Itt definiáljuk a postgres-data volumenet